# Generated by Django 4.2.5 on 2023-09-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(null=True)),
                ('title', models.TextField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'show',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('air_date', models.DateField()),
                ('title', models.TextField()),
                ('slug', models.TextField()),
                ('season_number', models.IntegerField()),
                ('number', models.IntegerField()),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_show', to='nstv.show')),
            ],
            options={
                'db_table': 'episode',
            },
        ),
    ]
