# Generated by Django 5.0.2 on 2024-03-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0002_delete_nzbdownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='NZBDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nzb_id', models.TextField(default=None, null=True)),
                ('site', models.TextField(default=None, null=True)),
                ('title', models.TextField(default=None, null=True)),
                ('url', models.TextField(default=None, null=True)),
                ('status', models.TextField(default=None, null=True)),
                ('status_two', models.TextField(default=None, null=True)),
            ],
            options={
                'db_table': 'nzb_download',
            },
        ),
    ]
