# Generated by Django 4.2.5 on 2023-09-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0003_alter_episode_number_alter_episode_season_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='slug',
        ),
    ]
