# Generated by Django 5.0.2 on 2024-03-12 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0003_nzbdownload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nzbdownload',
            name='status_two',
        ),
    ]
