# Generated by Django 6.0.2 on 2026-03-01 19:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0004_remove_nzbdownload_status_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='first_aired',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='show',
            name='network',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='overview',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='poster_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='status',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(blank=True, default=''),
        ),
    ]
