# Generated by Django 5.0.2 on 2024-05-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0004_remove_nzbdownload_status_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='season_number',
            field=models.TextField(null=True),
        ),
    ]
