# Generated by Django 4.2.5 on 2023-09-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0005_alter_episode_air_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='nstv.show'),
        ),
    ]
