# Generated by Django 6.0.2 on 2026-03-07 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0005_movie_overview_movie_rating_show_first_aired_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.TextField()),
                ('file_size', models.BigIntegerField()),
                ('quality_info', models.JSONField()),
                ('reason', models.TextField(default='Lower quality duplicate')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nstv.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nstv.movie')),
                ('show', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nstv.show')),
            ],
            options={
                'db_table': 'duplicate_deletion_log',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
