# Generated by Django 5.2.11 on 2026-03-15 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0005_alter_episode_season_number'),
        ('nstv', '0006_duplicatedeletionlog'),
    ]

    operations = [
    ]
