# Generated by Django 4.2.5 on 2023-09-16 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0006_alter_episode_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='on_disk',
            field=models.BooleanField(default=False),
        ),
    ]
