# Generated by Django 4.2.5 on 2023-09-16 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0007_episode_on_disk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='number',
            new_name='episode_number',
        ),
    ]
