# Generated by Django 4.2.5 on 2023-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0009_show_anime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField(default=None)),
                ('title', models.TextField()),
                ('release_date', models.DateField(default=None)),
                ('genre', models.TextField()),
                ('director', models.TextField()),
                ('on_disk', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.RemoveField(
            model_name='show',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='show',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='show',
            name='gid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
