# Generated by Django 4.2.5 on 2023-09-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0010_movie_remove_show_end_date_remove_show_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gid',
        ),
    ]
