# Generated by Django 4.2.5 on 2023-09-24 02:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0011_remove_movie_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=None),
        ),
    ]
