# Generated by Django 4.2.5 on 2023-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0013_alter_movie_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='gid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
