# Generated by Django 4.2.5 on 2023-10-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstv', '0014_movie_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
